//! Event types for the sonos-stream crate
//!
//! This module defines the event envelope types (EnrichedEvent, EventSource, EventData)
//! and re-exports canonical state types from sonos-api. The actual per-service state
//! structs live in sonos-api; sonos-stream wraps them in EventData for transport.

use std::net::IpAddr;
use std::time::{Duration, Instant, SystemTime};

use crate::registry::RegistrationId;

// Re-export sonos-api state types for convenience
pub use sonos_api::services::av_transport::state::AVTransportState;
pub use sonos_api::services::group_management::state::GroupManagementState;
pub use sonos_api::services::group_rendering_control::state::GroupRenderingControlState;
pub use sonos_api::services::rendering_control::state::RenderingControlState;
pub use sonos_api::services::zone_group_topology::state::ZoneGroupTopologyState;

// Re-export topology sub-types used by consumers (e.g. sonos-state decoder tests)
pub use sonos_api::services::zone_group_topology::events::{
    NetworkInfo, SatelliteInfo, ZoneGroupInfo, ZoneGroupMemberInfo,
};

/// An enriched event that includes context and source information
#[derive(Debug, Clone)]
pub struct EnrichedEvent {
    /// Registration ID this event belongs to
    pub registration_id: RegistrationId,

    /// IP address of the speaker that generated this event
    pub speaker_ip: IpAddr,

    /// UPnP service that generated this event
    pub service: sonos_api::Service,

    /// Source of this event (UPnP notification or polling)
    pub event_source: EventSource,

    /// Wall-clock time at which this event was constructed.
    ///
    /// Suitable for display and logging. **Not** suitable for ordering: it can
    /// step backwards when NTP corrects the clock. Use [`Self::observed_at`] to
    /// order two events against each other.
    pub timestamp: SystemTime,

    /// Monotonic instant at which the values in `event_data` were *observed*.
    ///
    /// This is what downstream write ordering keys on, and the two sources
    /// define it differently on purpose:
    ///
    /// - A UPnP NOTIFY: when the notification arrived at the callback server.
    ///   That is the earliest moment the process could have known these values,
    ///   and it precedes parsing, channel hops, and worker scheduling.
    /// - A poll: when the poll *request* was issued. A poll response describes
    ///   the device as of the request, exactly like `fetch()`, so stamping it on
    ///   arrival would let a slow poll displace a value observed later.
    ///
    /// It is an `Instant` rather than a `SystemTime` because it exists solely to
    /// be compared, and only the monotonic clock makes comparison sound.
    pub observed_at: Instant,

    /// The actual event data
    pub event_data: EventData,
}

impl EnrichedEvent {
    /// Create a new enriched event observed right now.
    ///
    /// Only correct when construction and observation coincide. A UPnP NOTIFY
    /// (observed at the callback server) and a poll (observed when the request
    /// went out) must use [`Self::observed_at`] instead.
    pub fn new(
        registration_id: RegistrationId,
        speaker_ip: IpAddr,
        service: sonos_api::Service,
        event_source: EventSource,
        event_data: EventData,
    ) -> Self {
        Self::observed_at(
            registration_id,
            speaker_ip,
            service,
            event_source,
            event_data,
            Instant::now(),
        )
    }

    /// Create an enriched event whose values were observed at a known instant.
    ///
    /// `observed_at` must be the instant the *device state* was seen, not the
    /// instant this struct is built — see the field docs on
    /// [`Self::observed_at`].
    pub fn observed_at(
        registration_id: RegistrationId,
        speaker_ip: IpAddr,
        service: sonos_api::Service,
        event_source: EventSource,
        event_data: EventData,
        observed_at: Instant,
    ) -> Self {
        Self {
            registration_id,
            speaker_ip,
            service,
            event_source,
            timestamp: SystemTime::now(),
            observed_at,
            event_data,
        }
    }
}

/// Source of an event - indicates whether it came from UPnP events or polling
#[derive(Debug, Clone)]
pub enum EventSource {
    /// Event came from a UPnP NOTIFY message
    UPnPNotification {
        /// UPnP subscription ID
        subscription_id: String,
    },

    /// Event was generated by polling device state
    PollingDetection {
        /// Current polling interval
        poll_interval: Duration,
    },
}

/// Event data - complete event information for each service.
///
/// Variants reference canonical State types from sonos-api.
/// Both UPnP events (via `into_state()`) and polling (via `poll()`)
/// produce the same State types, ensuring parity.
#[derive(Debug, Clone)]
pub enum EventData {
    /// AVTransport service state
    AVTransport(AVTransportState),

    /// RenderingControl service state
    RenderingControl(RenderingControlState),

    /// ZoneGroupTopology service state
    ZoneGroupTopology(ZoneGroupTopologyState),

    /// GroupManagement service state
    GroupManagement(GroupManagementState),

    /// GroupRenderingControl service state
    GroupRenderingControl(GroupRenderingControlState),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_enriched_event_creation() {
        let reg_id = RegistrationId::new(1);
        let ip: IpAddr = "192.168.1.100".parse().unwrap();
        let service = sonos_api::Service::AVTransport;
        let source = EventSource::UPnPNotification {
            subscription_id: "uuid:123".to_string(),
        };
        let data = EventData::AVTransport(AVTransportState {
            transport_state: Some("PLAYING".to_string()),
            transport_status: None,
            speed: None,
            current_track_uri: None,
            track_duration: None,
            track_metadata: None,
            rel_time: None,
            abs_time: None,
            rel_count: None,
            abs_count: None,
            play_mode: None,
            next_track_uri: None,
            next_track_metadata: None,
            queue_length: None,
        });

        let event = EnrichedEvent::new(reg_id, ip, service, source, data);

        assert_eq!(event.registration_id, reg_id);
        assert_eq!(event.speaker_ip, ip);
        assert_eq!(event.service, service);
    }
}
